spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_app
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
      enable_lazy_load_no_trans: true
  mail:
    host: smtp.gmail.com
    port: 25
    username: ngotuankiet12347@gmail.com
    password: iqen aszq byda byug
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 465723517289-t72vn771k7098lrvle60plgnmaift9f5.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 335365422838659
            clientSecret: fd7278c61f691045efc5788666b43fbb
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}" # Note that facebook now mandates the use of https redirect URIs, so make sure your app supports https in production
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,picture.width(250).height(250)
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
    accessExpiration: 1500000
    refreshExpiration: 604800000
  cors:
    allowedOrigins: http://localhost:3000 # Comma separated list of allowed origins
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
api:
  prefix: api/v1
cloud:
  cloudName: dzumda5fa
  apiKey: 959631823469922
  apiSecret: NFULtoFFUlC6qCPN1BSiRw5KUGk
  secure: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE